---
Name: hubspot
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Kraftausdruck\Extensions\HubSpotConfigExtender
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Kraftausdruck\Extensions\HubSpotRequestExtender